# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\abdul\Desktop\gmail_app_old\gmail_app_old\ui\email_input.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import var


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 149)
        Dialog.setStyleSheet("QLineEdit{\n"
"    border:  1px solid #777;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QWidget{\n"
"    background: #eff2f8;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_linedit = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.label_linedit.setFont(font)
        self.label_linedit.setStyleSheet("QLabel {\n"
"    color: #555\n"
"}")
        self.label_linedit.setAlignment(QtCore.Qt.AlignCenter)
        self.label_linedit.setObjectName("label_linedit")
        self.gridLayout.addWidget(self.label_linedit, 0, 0, 1, 1)
        self.lineEdit_email = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_email.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lineEdit_email.setFont(font)
        self.lineEdit_email.setStyleSheet("QLineEdit{\n"
"    border: 1px solid #ddd;\n"
"    border-radius: 3px;\n"
"    background: #fff;\n"
"}")
        self.lineEdit_email.setFrame(False)
        self.lineEdit_email.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_email.setClearButtonEnabled(True)
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.gridLayout.addWidget(self.lineEdit_email, 0, 1, 1, 2)
        self.pushButton_send = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.pushButton_send.setFont(font)
        self.pushButton_send.setStyleSheet("QPushButton {\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: rgba(0, 138, 191);\n"
"    padding: 5px 28px;\n"
"    color: rgb(255, 255, 255);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(0, 138, 191, 0.6);\n"
"    opacity: 0.2\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: rgb(0, 138, 191);\n"
"    }")
        self.pushButton_send.setObjectName("pushButton_send")
        self.gridLayout.addWidget(self.pushButton_send, 2, 1, 1, 1)
        self.label_status = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_status.setFont(font)
        self.label_status.setStyleSheet("QWidget{\n"
"    background: #eff2f8;\n"
"}")
        self.label_status.setText("")
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setObjectName("label_status")
        self.gridLayout.addWidget(self.label_status, 3, 0, 1, 3)
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("/* Base style for the progress bar */\n"
"QProgressBar {\n"
"    border: none;                   /* Remove border */\n"
"    border-radius: 2px;            /* Rounded corners */\n"
"    background-color: #fff;      /* Light gray background */\n"
"    text-align: center;             /* Center the text */\n"
"    color: #000;  \n"
"    height: 2px;  \n"
"}\n"
"\n"
"/* Style for the progress chunk (filled part) */\n"
"QProgressBar::chunk {\n"
"    background-color: #3366FF;      /* Blue color for the progress */\n"
"    border-radius: 2px;            /* Match rounded corners */\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 1, 0, 1, 3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", var.window_title))
        self.label_linedit.setText(_translate("Dialog", "Forward To:"))
        self.pushButton_send.setText(_translate("Dialog", "SEND"))
